#!/bin/sh

commit_message="$(cat $1)"
requiredPattern="^(feat|fix): .*$"

if ! [[ $commit_message =~ $requiredPattern ]]; then
  echo "🚨 Invalid commit message! 😕"
  echo "The commit message must start with 'feat: ' or 'fix: ' and follow the Conventional Commits format."
  exit 1
fi
